### ISSUE TITLE
Identify and implement core IAC changes

### ISSUE THREAD

**Issue by Davsarper** [alan-turing-institute/data-safe-haven-team#28]
# Goal Title

Make DSH deployment more robust and development easier through using IAC and configuration management.

## Description

- Take advantage of IAC and configuration management in the DSH codebase which will
  - Make deployments faster
  - Make deployments more reliable
  - Make development easier
- Move away from non-idempotent, bespoke scripts (Powershell, bash, cloud-init)

### Components

- [Nexus allowlist](https://github.com/alan-turing-institute/nexus-allowlist)

## Definition of Done

On the release of a new major version which removes legacy, script-based deployment.

## Details

- RACI
  - Accountable team or person: @jemrobinson @jimmadge
  - Responsible team or person: REG
  - Informed and consulted people: @martintoreilly @KirstieJane 
- Estimated effort FTE: 1.0
  - RAM: 0.05

#### August
- REG: 1

## Task and issue breakdown
Breakdown in specific tasks of maximum a month duration, tasks and issues may be added as necessary
Issues may span across repositories when necessary

- [ ] [Pulumi migration meta issue](https://github.com/alan-turing-institute/data-safe-haven/issues/1292)
- [Python migration milestone](https://github.com/alan-turing-institute/data-safe-haven/milestone/19)

## Checklist
- [x] This Story have been agreed with project members, it tackles prioritised work
  - [ ] If not: Label as ForPrioritisation so it discussed in the next monthly meeting, do not set a status  
- [ ] I have included this Story in the agreed upon Milestone, set status as Planned
  - [ ] If not: set status as Backlog, to be Planned via weekly meetings/discussions
- [ ] The work to be done is likely to span over a month
- [ ] I have broken down the work in monthly issues and added them above
- [ ] I have labeled this issue according to its main project: SATRE, TRESA, CORE DSH (ELA) or other (please agree and create a new label if necessary)
- [ ] I have stimated the total effort and added it in the body (under Details) but left the issue field blank

### 5 February to 8 April 2024

Over this period the story has not been prioritised/resourced as much, focusing on identifying and scoping future work which will be a priority after v4.2 release. The DSH code repo contains milestones that reflect related and planned issues (V5.x milestones) https://github.com/alan-turing-institute/data-safe-haven/milestones

Additionally a first version of the codebase roadmap has been put in place, linking to milestone but also recording potential desired features that are not currently planned to implement. A roadmap is a desired/required document to have in place for software funding opportunities https://github.com/alan-turing-institute/data-safe-haven/blob/develop/ROADMAP.md

Some key maintenance work have been done like:
- Changing to Azure flexible postgreSQL as previous version will be deprecated https://github.com/alan-turing-institute/data-safe-haven/pull/1735

### 9 January to 5 February 2024

Numerous small improvements and bug fixes from previous changes to context/config, Mostly focused on internal structure, making the code consistent and removing bugs.
- [Improve handling of SRE names](https://github.com/alan-turing-institute/data-safe-haven/pull/1699)
- [Ensure Pulumi container is created](https://github.com/alan-turing-institute/data-safe-haven/pull/1711)
- [Update private link scope to AzureNative v2](https://github.com/alan-turing-institute/data-safe-haven/pull/1713)
- [Updates to context handling](https://github.com/alan-turing-institute/data-safe-haven/pull/1716)
- [Linting changes](https://github.com/alan-turing-institute/data-safe-haven/pull/1718)
- [Bump linter version](https://github.com/alan-turing-institute/data-safe-haven/pull/1719)

### 5 December to 8 January 2024

- Pydantic/configuration changes ready for review
- Opened issues for further enhancements fixes

### 1 November 4 December

A lot of work on Pydantic and configuration [PR](https://github.com/alan-turing-institute/data-safe-haven/pull/1661)

- Code is shorter, clearer, more robust as it uses the features of the Pydantic library for serialisation and validation, where before we had created our own.
- However the new structure doesn't allow for optional items in configuration, which was relied on by existing commands.

While the new Pulumi code is better, we are finding incompatibilities that would require extensive work to adapt to the old code, only to deprecate them in the future as we let go of PowerShell. We are choosing not to make these changes.

Work is focus on making the new code better, rather than in new features.

### 10 October to 30 October 2023
- Focus on thinking and structuring, trying for commands to be clearer for users
  - Planning/discussing how to structure command line interface [issue](https://github.com/alan-turing-institute/data-safe-haven/issues/1651)
  - estructuring the init command  [PR](https://github.com/alan-turing-institute/data-safe-haven/pull/1655)
  - Set of issues around user experience, interface, structure based on experience with trial run: [milestone](https://github.com/alan-turing-institute/data-safe-haven/milestone/20)
- Continued work on login flow adjustments:  [PR](https://github.com/alan-turing-institute/data-safe-haven/pull/1617). This should make the user experience less confusing as well as help avoid problems if a user is signed into the "wrong" Az CLI or Pulumi accounts 

### 19 September to 9 October
- Improvements to error messages during Pulumi deployment to make it easier to use the command line interface correctly [PR#1624](https://github.com/alan-turing-institute/data-safe-haven/pull/1624)
- Deployment walkthrough session to find issues/bugs and share understanding
- Pulumi
  - Testing and debugging Pulumi: [Fix order of operations for Pulumi actions](https://github.com/alan-turing-institute/data-safe-haven/pull/1618)
  - Lots of thinking and talking about code structure:  [Changing handling of AZ login and Pulumi login](https://github.com/alan-turing-institute/data-safe-haven/pull/1618) Aiming to be more versatile/less opinionated. Also fixes some edge case bugs where a users is logged into the 'wrong' account.
- Nexus allowlist development: Introduce an alternative to entr for updating allowlists [PR](https://github.com/alan-turing-institute/nexus-allowlist/pull/32)

### 14 August to 18 September

- [Pulumi: drop custom whoami function](https://github.com/alan-turing-institute/data-safe-haven/pull/1564)
- [Pulumi: SRE DNS filtering](https://github.com/alan-turing-institute/data-safe-haven/pull/1566)
- [Pulumi: deployment fixes](https://github.com/alan-turing-institute/data-safe-haven/pull/1577)
- [Pulumi: Improve SSL labs score](https://github.com/alan-turing-institute/data-safe-haven/pull/1576)
- [Pulumi: Allow only specified user IP addresses](https://github.com/alan-turing-institute/data-safe-haven/pull/1572)
- [Pulumi: Lazy load Guacamole users when performing admin tasks](https://github.com/alan-turing-institute/data-safe-haven/pull/1568)
- [Update Pulumi Docker images](https://github.com/alan-turing-institute/data-safe-haven/pull/1565)
- Pulumi: Added SRE networking  [Implemented in PR 1555](https://github.com/alan-turing-institute/data-safe-haven/pull/1555)
- Pulumi: Added SRE routing    [Implemented in PR 1560](https://github.com/alan-turing-institute/data-safe-haven/pull/1560)

#### Pulumi migration
- [Switched CLI interface to Typer](https://github.com/alan-turing-institute/data-safe-haven/pull/1502)
- [Nexus allowlist](https://github.com/alan-turing-institute/nexus-allowlist)
- [Migrated pyproject to PyPA standard and hatch](https://github.com/alan-turing-institute/data-safe-haven/pull/1506)
- alan-turing-institute/data-safe-haven/pull/1510 providing a better config structure
- Pulumi configuration

**Comment by Davsarper** [comment]
The updates mostly revolve around either pUlumi Migraiton or powershell, do update after monthly

**Comment by Davsarper** [comment]
October: still a priority, other work may get in the way but still want to focus on it

**Comment by Davsarper** [comment]
Extended report for 9 October, more detials and PRs
Pulumi migration
        [more permissive tenant rules to fix authentication issue](https://github.com/alan-turing-institute/data-safe-haven/pull/1610) which prevented the use of the CLI for deployment/management
        [Fix guacamole database timeout issue](https://github.com/alan-turing-institute/data-safe-haven/pull/1608) which would lead to secure desktop being unusable
        [Described deployment error, unable to find secrets](https://github.com/alan-turing-institute/data-safe-haven/issues/1615)
        [Described deployment error, key error](https://github.com/alan-turing-institute/data-safe-haven/issues/1613) possibly due to being connected to the 'wrong' pulumi backend
        [Discussed how to handle AZ CLI and Pulumi account login](https://github.com/alan-turing-institute/data-safe-haven/issues/1511). Automatic handling may lead to unexpected problems and confuse users. Possibly related to the key error above.
        [Draft PR](https://github.com/alan-turing-institute/data-safe-haven/pull/1617)
    Nexus Allowlist
        Investigating [selectors not updating](https://github.com/alan-turing-institute/nexus-allowlist/issues/27) with [potential fix](https://github.com/alan-turing-institute/data-safe-haven/pull/1609)

**Comment by Davsarper** [comment]
# Dec planning

Top priority, have been doing a lot of work towards quality. There is really a lot more to be done (getting rid of MS VMs, imporve storage, configration checks, many ideas). This could use a lot of people, but with a specific profile.

This work is a big improvement but also change, it needs to be correctly handled with deployed DSHs and also with how we go about outreach and community/user-base creation. We require a clear roadmap of when we are releasing this version and deprecating the powershell V.

V5 may be a thing of late 2024.

- Dec work: Code tidying, configuration of commands, bug fixes. NO new features in the short term
- Future work: Proposal, even if internal, to get a clear picture of what we need to do, want to do, what it will achieve. This requires a product roadmap, expected changes that this will imply for existing users.

**Comment by Davsarper** [comment]
# Jan Planning
We are continuing with the previous resourcing. May be a good period to consider goals within this story and how they are met

**Comment by harisood** [comment]
# January planning

Focus of January is:
* Continue work on ongoing/live PRs/issues
* Develop the product roadmap for v5.
  * This should end with a project board specifically for v5

**Comment by Davsarper** [comment]
February: there might be some best effort checks to ensure in March it runs so it can be a priority again

**Comment by Davsarper** [comment]
As we pick this up again April will be the time to think again about the work to do so this becomes a top priority in May

**Comment by Davsarper** [comment]
Top priority in May:
- https://github.com/alan-turing-institute/data-safe-haven/milestone/20

**Comment by Davsarper** [comment]
Top priority, there is quite a lot to do. Target date moved to end of June to make it to RSEcon
- https://github.com/alan-turing-institute/data-safe-haven/milestone/20
