### ISSUE TITLE
Identify sustainability pathways post-SATRE

### ISSUE THREAD

**Issue by Davsarper** [alan-turing-institute/data-safe-haven-team#34]
# Goal Title
Maximising the potential and impact from this project, whatever that looks like

## Description
- Determine what the project team means by sustainability (i.e. what happens to this project after it is no longer funded at Turing).
- - Review how other TRE teams across the UK are tackling this question
- Create roadmap of activity for the critical path to sustainability
- Action critical path for sustainability (most likely with PIs)

## Definition of Done
When we have a roadmap for sustainability pathways and are undertaking it

## Details
- RACI
  - Accountable team or person: RAM
  - Responsible team or person: REG, RCM, RPM
  - Informed and consulted people:
- Estimated effort FTE: 
  - RAM: 0.15
  - RPM: 0.05 (further work can be considered part of #53 )
  - REG: 0.05 (?)

## Task and issue breakdown
Breakdown in specific tasks of maximum a month duration, tasks and issues may be added as necessary
Issues may span across repositories when necessary

- issue alan-turing-institute/data-safe-haven-team#X
- issue alan-turing-institute/data-safe-haven#X
- issue alan-turing-institute/trusted-research
- issue sa-tre/satre-specification#X
- issue sa-tre/satre-team#X

## Checklist
- [x] This Story have been agreed with project members, it tackles prioritised work
  - [ ] If not: Label as ForPrioritisation so it discussed in the next monthly meeting, do not set a status  
- [x] I have filled in the Team Accountabe field
- [x] I have included this Story in the agreed upon Milestone, set status as Planned
  - [ ] If not: set status as Backlog, to be Planned via weekly meetings or async discussions
- [x] The work to be done is likely to span over a month
- [ ] I have broken down the work in monthly issues and added them above
- [x] I have labeled this issue according to its main project: SATRE, TRESA, CORE DSH (ELA) or other (please agree and create a new label if necessary)
- [x] I have stimated the total effort and added it in the body (under Details) but left the issue field blank

**Comment by Davsarper** [comment]
Are we sure RAM is accountable? could it be CO-Is?

**Comment by Davsarper** [comment]
@jemrobinson & REG what effort from you do you think this would take? Considering you are not Accountable but do contribute to it and are Responsible.
This story is different from #51 though it may share some tasks

**Comment by jemrobinson** [comment]
This feels like it might involve a few strategy/planning sessions but then be done. What do you think?

**Comment by Davsarper** [comment]
It does feel like that maybe, after work from RAM to identify possibilities and prepare the sessions. For REG the effort may then be about 0.05 while active (one 2 hour meeting a week, while ongoing)

**Comment by Davsarper** [comment]
# Dec meeting

Moved to February, around when we expect DARE phase 2 to be announced
