### ISSUE TITLE
Events plan and budget

### ISSUE THREAD

**Issue by Davsarper** [alan-turing-institute/data-safe-haven-team#42]
Event and conference attendance is part of the project, budgeted in ELA and SATRE. We need to create an events plan to decide which to attend and our actitivites there.

Events to consider:

- SATRE midproject showcase
- RSEcon 23: submitted for talk and workshop
- Others?

Budget will be prioritised for active participation in relation with project activity and goals, after that the remaining will be used to allow as many team members as possible to attend events that are of interest to them and their prof. development (this could be done mixing project and REG internal funds).

## Tasks

- [ ] Complete list of events @harisood @JimMadge @jemrobinson @craddm @edwardchalstrey1 
- [ ] Determine intended participation
- [ ] Estimate costs and check budget @Davsarper 
- [ ] Estimate budget remaining for attendance without active participation
- [ ] Team members to express preferences and interests

Slack conversation: https://alan-turing-institute.slack.com/archives/C0428BBM94M/p1685433337712409

**Comment by Davsarper** [comment]
tracked-by:alan-turing-institute/data-safe-haven-team/issues#35

**Comment by harisood** [comment]
I think there's a piece of work to identify relevant conferences/events/opportunities. @Davsarper something for us to discuss?
