### ISSUE TITLE
Project Strategy and Ways of work

### ISSUE THREAD

**Issue by Davsarper** [alan-turing-institute/data-safe-haven-team#43]
# Goal Title
The aim is to develop a project strategy and revise best ways of work to achieve it

## Description
Through several strategy sessions we will:
- Define our north star (vision & mision)
- Establish the project pilars or areas, defining what success looks like for each
- Prioritise the measure of success, which are essential to consider the project succesful?
- Identify work required to achieve success
- Allocate work by team
- Produce an initial roadmap
- Evaluate required effort for the work against team capacity
- Develop and agree new ways of work, including meeting structure and use of project's repositories and projects

## Definition of Done
When will this be considered as succesfully completed?

## Details
- RACI
  - Accountable team or person: RAM, RPM
  - Responsible team or person: REG, RCM, CO-Is, Others
  - Informed and consulted people:
- Estimated effort FTE
  - High
 
## Task and issue breakdown
- [ ] Plan sessions
- [ ] Conduct and facilitate sessions
- [ ] Strategy output: presentations and materials with outputs
- [ ] #44

## Checklist
- [ ] This Story have been agreed with project members, it tackles prioritised work
  - [ ] If not: Label as ForPrioritisation so it discussed in the next monthly meeting, do not set a status  
- [ ] I have filled in the Team Accountabe field
- [ ] I have included this Story in the agreed upon Milestone, set status as Planned
  - [ ] If not: set status as Backlog, to be Planned via weekly meetings or async discussions
- [ ] The work to be done is likely to span over a month
- [ ] I have broken down the work in monthly issues and added them above
- [ ] I have labeled this issue according to its main project: SATRE, TRESA, CORE DSH (ELA) or other (please agree and create a new label if necessary)
- [ ] If known: sum the total effort (points) of tracked issues and add it on the body
- [ ] Select a Story level of effort in the project fields

## Reporting

This story resulted in a project clear strategy and roadmap, as well as a first (since updated) proposal for ways of work.

Related work for this story continues in #54

**Comment by Davsarper** [comment]
@harisood I want to close this story considering we delivered what is was set out to do, I wonder though where to properly reflect ongoing work related to strategy and prioritisation, I am especifically thinking of the meeting we will have to reprioritise due to limited resources. 
Do you see room for that work in your existing stories, on #34 perhaps (maybe wiht proper updates)?
It could also fit under my story #54 but feels different

**Comment by harisood** [comment]
I wonder if we should be having cadenced reviews of the strategy to make sure it's still relevant (e.g. quarterly), in which case we should keep this issue open?

**Comment by Davsarper** [comment]
On one hand it makes sense, on the other if everythign is "ongoing" we loose some insight about the workload and have a permanent issue for discrete tasks. If we keep it, then we should adjust effort

**Comment by Davsarper** [comment]
I am reopening as after 1st planning meeting it seems like the ongiong changes to WoW, planning meetings and strtegic decisions will continue to happen and they do fit here. Will evaluate wheter or not to keep WoW as part of #54 or not

**Comment by harisood** [comment]
# Jan planning

Plan for an explicit strategy revisit session in Feb

**Comment by Davsarper** [comment]
@Davsarper wants to make this as much as a priority as possible to:
- Create due reports
- Revisit reports and monthlies format
- Propose and discuss PIs WoW

**Comment by Davsarper** [comment]
In May still want to do the above and (but may not be a must happen so not priority):
- work with @martintoreilly on roadmap v2
