### ISSUE TITLE
RSEcon23 + UK TRE satellite event: organise, plan and deliver

### ISSUE THREAD

**Issue by Davsarper** [alan-turing-institute/data-safe-haven-team#46]
## Context

RSEcon23 has been prioritised as a major event for the DSH project with several activities to deliver. All team members will get their attendance covered which means we also need to collaboratively deliver the activities.

Dates: 4th-9th September (4th being the satellite event)
Location: Swansea university

Delivered activities
 - UK TRE Community event: 4th Sept all day
 - [SATRE talk: 5th Sept 13.30-15.00 / Track D Platforms](https://virtual.oxfordabstracts.com/#/event/4430/submission/63)
 - [DSH Workshop: 6th Sept 09.00-10.30/ Track D](https://virtual.oxfordabstracts.com/#/event/4430/submission/64)

Internal [Spreadsheet to organise](https://thealanturininstitute-my.sharepoint.com/:x:/g/personal/dsarmientoperez_turing_ac_uk/EdAdA8J2zLVIiLHy3VO9OOcB_zvlf3MbTEMMHWNOFJ2jmg?e=SkwieB) 

## Tasks
- [ ] Confirm registration
- [ ] Book accomodation, each member directly then claim expenses
- [ ] Plan travel and book where possible, via Gray Dawes (contact David if you do not have access)
- [ ] Plan satellite event, DARE supported
  - [ ] Venue requirements and confirmation
  - [ ] Agenda
  - [ ] Comms and registration
  - [ ] Confirm members delivering and format (confirm travel plans)
- [ ] Plan DSH workshop
  - [ ] Confirm slot
  - [ ] Review and update content
- [ ] SATRE talk
  - [ ] Confirm slot and speakers
  - [ ] Prepare content   

## Story
This issue contributes to #42

**Comment by Davsarper** [comment]
Accomodation is available to book in Swansee university until end of July, we need to have clarity of days for everyone in order to correctly book
👉 [link](https://conferences.swansea-union.co.uk/event/rsecon23-the-seventh-annual-conference-for-research-software-engineering/85154)

**Comment by Davsarper** [comment]
[RSEcon programme](https://virtual.oxfordabstracts.com/#/e/RSECon23/program)

Our dates:
- UK TRE Community event: 4th Sept all day
- SATRE talk: 5th Sept 13.30-15.00 / Track D Platforms
- DSH Workshop: 6th Sept 09.00-10.30/ Track D

**Comment by edwardchalstrey1** [comment]
> Accomodation is available to book in Swansee university until end of July, we need to have clarity of days for everyone in order to correctly book 👉 [link](https://conferences.swansea-union.co.uk/event/rsecon23-the-seventh-annual-conference-for-research-software-engineering/85154)

I've booked 3rd-6th

**Comment by harisood** [comment]
I'll be the same, should I book myself or are we doing a group booking?

**Comment by edwardchalstrey1** [comment]
> I'd ideally go 3rd-7th if poss! @edwardchalstrey1 you not staying for the Thursday?
> 
> Should we book independently or @Davsarper is the plan one big group booking? Should we coordinate with the rest of REG?

@harisood yes I'll leave Thursday evening after the conference ends

**Comment by Davsarper** [comment]
Because of the booking system accomodation has to be booked individually, if you can and are willing go ahead and book then submit the expenses; if you can't we will ask Martin.
For travel, do coordinate but again it has to be booked individually. This time via gray dawes please, you have to access gray dawes and see about how much it will cost, submit the travel form (excel sheet) to me and Martin for approval, then actually book.
@harisood and @JimMadge you should use the SATRE project code (R-DARE-001), everyone else the core one (D-ELA-005)

**Comment by edwardchalstrey1** [comment]
> This time via gray dawes please

@Davsarper you'd prefer we didn't pay and claim on Certify?

**Comment by Davsarper** [comment]
Policies do ask that as much as possible we book travel and accomodation via gray dawes, expenses should be minimised, accomodation cannot be booked there this time so it goes via certify but travel should. If you happen to have already booked on your own that's ok but it is not the preffered option.
