### ISSUE TITLE
Manage codebase releases and testing

### ISSUE THREAD

**Issue by Davsarper** [alan-turing-institute/data-safe-haven-team#50]
# Goal Title
_What will this work achieve?_
Support for deployments of the Data Safe Haven at Turing and beyond

## Description
- Ensure that all aspects of code are working before tagging a release
- Run manual deployment tests
- Run penetration tests as needed

[Manage codebase releases and testing](https://github.com/alan-turing-institute/data-safe-haven-team/issues/50) and [Codebase maintenance](https://github.com/alan-turing-institute/data-safe-haven-team/issues/47) are closely related but the first one is specifically around fixes/testing of our current code before tagging a release while the second one is generic updates/bug-fixes that aren't tied to us being about to release something

## Definition of Done
_When will this be considered as succesfully completed?_
Ongoing

## Details
- RACI
  - Accountable team or person: @jemrobinson 
  - Responsible team or person: Data Safe Haven team
  - Informed and consulted people: TRESA team, Data Safe Haven community
- Estimated effort in total FTE: 0.1 (approximately 2 weeks work, 3 times annually)

#### August
- REG: 0.5

### References

- [Versioning documentation](https://github.com/alan-turing-institute/data-safe-haven/blob/develop/VERSIONING.md)
- [GitFlow model and release branch process](https://github.com/alan-turing-institute/data-safe-haven/blob/develop/CONTRIBUTING.md#contributing-through-github)

## Task and issue breakdown
Breakdown in specific tasks of maximum a month duration, tasks and issues may be added as necessary
Issues may span across repositories when necessary

- https://github.com/alan-turing-institute/data-safe-haven-team/issues/21

## Checklist
- [ ] This Story have been agreed with project members, it tackles prioritised work
  - [ ] If not: Label as ForPrioritisation so it discussed in the next monthly meeting, do not set a status  
- [x] I have filled in the Team Accountable field
- [ ] I have included this Story in the agreed upon Milestone, set status as Planned
  - [ ] If not: set status as Backlog, to be Planned via weekly meetings or async discussions
- [x] The work to be done is likely to span over a month
- [x] I have broken down the work in monthly issues and added them above
- [ ] I have labeled this issue according to its main project: SATRE, TRESA, CORE DSH (ELA) or other (please agree and create a new label if necessary)
- [ ] If known: sum the total effort (points) of tracked issues and add it on the body
- [ ] Select a Story level of effort in the project fields

### 5 February to 8 April 2024

Having completed development of v4.2.0 we prepared the release which included preparing a release branch and deployment in an environment for pen testing.

Extensive time was allocated to deploying and the errors/bugs that arose, as well as preparing for pen testing (this included deployment but also requesting specific tests like the removal of certain hardcoded IPs)

Pen testing was arranged and carried out, managing to spend within the 2023-2024 FY. iStorm kept better communications than last time and did not find concerning issues.
- Results from the pen test only found issues we had previously seen and are happy to accept as being not of concern or have already mitigated

### 19 September to 9 October
- Pen testing done: little found

### 14 August to 18 Septmber
- Penetration tested arranged and will be done in September
- Preparation for release v4.1.0: Deployment of different SRE variants, Security checklist
- Reviewing v4.1.0:  No significant problems is deployment logs, Problems found in security checklist relating to MSRDS

### 10 July to 14 August 2023

-  Working on [Release 4.1.0](https://github.com/alan-turing-institute/data-safe-haven/issues/1544): fixes bugs and introduces necessary updates

**Comment by Davsarper** [comment]
@jemrobinson what would be the headline of what 4.1 release delivers?

**Comment by jemrobinson** [comment]
Release notes here: https://github.com/alan-turing-institute/data-safe-haven/releases/tag/untagged-559a72d3d8bbb76d2aeb

**Comment by Davsarper** [comment]
September was heavy with pen test and release, October may be quieter

**Comment by Davsarper** [comment]
# Dec planning

Working on a series of issues associated the last release

**Comment by Davsarper** [comment]
February action for @Davsarper , verify budget for another pen test and get in contact with iStorm

**Comment by Davsarper** [comment]
Needs to be a priority, work belongs to march but there will be follow up things. for exmaple:
- announcement: do we want to be loud about a last powershell version?
- No more support once the next release is out.

**Comment by Davsarper** [comment]
Patch release this month by @jemrobinson (please add issue)

**Comment by Davsarper** [comment]
Similar to last month there is a bug that needs fixing and making an associated patch release, not made yet because focus on development but will happen.

Priority yes, not a lot of time spent on it.

We are in patch mode, doing what needs done but not focusing on new releases.

**Comment by Davsarper** [comment]
Hoping to release 5.0.0 this month so this is a priority, work will happen late august after pen test tells us what to fix change

**Comment by Davsarper** [comment]
No longer using this story to track this work, instead tracked within specific milestones/releases
