### ISSUE TITLE
Manage grant opportunities and pipeline

### ISSUE THREAD

**Issue by Davsarper** [alan-turing-institute/data-safe-haven-team#51]
# Goal Title
What will this work achieve?

## Description
Specific aims

## Definition of Done
When will this be considered as succesfully completed?

## Details
- RACI
  - Accountable team or person:
  - Responsible team or person:
  - Informed and consulted people:
- Estimated effort in total FTE:

## Task and issue breakdown
Breakdown in specific tasks of maximum a month duration, tasks and issues may be added as necessary
Issues may span across repositories when necessary

- issue alan-turing-institute/data-safe-haven-team#X
- issue alan-turing-institute/data-safe-haven#X
- issue alan-turing-institute/trusted-research
- issue sa-tre/satre-specification#X
- issue sa-tre/satre-team#X

## Checklist
- [ ] This Story have been agreed with project members, it tackles prioritised work
  - [ ] If not: Label as ForPrioritisation so it discussed in the next monthly meeting, do not set a status  
- [ ] I have filled in the Team Accountabe field
- [ ] I have included this Story in the agreed upon Milestone, set status as Planned
  - [ ] If not: set status as Backlog, to be Planned via weekly meetings or async discussions
- [ ] The work to be done is likely to span over a month
- [ ] I have broken down the work in monthly issues and added them above
- [ ] I have labeled this issue according to its main project: SATRE, TRESA, CORE DSH (ELA) or other (please agree and create a new label if necessary)
- [ ] If known: sum the total effort (points) of tracked issues and add it on the body
- [ ] Select a Story level of effort in the project fields

**Comment by Davsarper** [comment]
This sotry is specific grant discussion, poroposal and submission.
Sustianability pathways #34 is mor estrategic, venues of funding and future possibilities

**Comment by Davsarper** [comment]
# Dec planning

Nothing immediate, this story goes into scanning and not doing mode

**Comment by Davsarper** [comment]
With your permission @JimMadge and according to what we discussed today in Monthly I am moving this story to Jan (to actually work on it), and changing it to RPM Accountable (as we defined accoutable as momentum generator).
We then want to:
- [ ] Capture know-how from PIs
- [ ] Organise roadmap into "packages" for calls: what different strands of work can be put together for calls, which calls? 
  - [ ] Potentially organise working sessions to do this / tie to strategy session 
- [ ] Organise a meeting with Partnerships and Philantropy to ask for their help in locating and preparing for opportunities (those packages should be done first)

**Comment by Davsarper** [comment]
It is a priority to at least think and plan, this story can be directly linked to PI work and how we better coordinate. So not a high resources story but still v important

**Comment by Davsarper** [comment]
In May we should review several identified grants. Still focus of team resources may be on other stories.
This has the potential to become a priority later on if we decide to submit one.

**Comment by Davsarper** [comment]
During May monthly meeting this story has been mentioned as a priority to apply to:

- https://www.ukri.org/opportunity/enhancing-biomedical-and-health-related-data-and-digital-platform-resources/

Prioritizing this story may require re-considering time in other stories.

@martintoreilly @KirstieJane How should we work together on this to submit? We need:

- Abstract
- Concrete idea of work to be done
- internal submission approval form, likely to be signed by Health SD
- Budget
- Request to allocate REG time (this one should be easy for us I expect)

**Comment by Davsarper** [comment]
[UKRI Digital Research Technical Professional Skills NetworkPlus](https://www.ukri.org/opportunity/ukri-digital-research-technical-professional-skills-networkplus/)

**Comment by Davsarper** [comment]
Two important opportunites:
- DARE UK phase 2#
 - SATRE 2/Kubernetes: need to ensure alignment to Turing 2.0 for us to participate in. This also contains an overarching stakeholder theme to coordinate 
 - Community management: DARE UK Community Groups call. 60-75k for groups to do specific things, we would lead in the name of the community
- NIHR: getting NHS data into SDEs, this HAS to be lead by a NHS trust. Already asked Health GC

**Comment by Davsarper** [comment]
In addition we have to submit our alignment paper to the ELT for continuation beyond March

**Comment by Davsarper** [comment]
Very important to submit to DARE's TRE early adoption with the proposal for a KUbernetes TRE on Isamabrd, working with UCL and Bristol. Very short turnarond
